---
# tasks file for create
- name: Setup Kubernetes
  hosts: servers
  tasks:

  - name: Criando arquivo k8s.conf
    become: yes
    file:
      path: /etc/modules-load.d/k8s.conf
      state: touch
      mode: u+rw,g+r,o+r

  - name: Adicionando módulos do kernel GNU/Linux
    become: yes
    lineinfile:
      path: /etc/modules-load.d/k8s.conf
      line: '{{item}}'
    with_items: 
      - 'br_netfilter' 
      - 'ip_vs ip_vs_rr'
      - 'ip_vs_sh' 
      - 'ip_vs_wrr' 
      - 'nf_conntrack_ipv4'

  - name: Instalando pacotes e dependências
    become: yes
    apt: name={{ item }} state=latest update_cache=yes
    loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

  - name: Adicionando Docker GPG/Key
    become: yes
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Adicionando Docker ao repositório /etc/apt/sources.list.d
    become: yes
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present

  - name: Update
    become: yes
    apt: update_cache=yes name=docker-ce state=latest

  - name: Instalando Docker
    become: yes
    pip:
      name: docker

  - name: Criando arquivo cgroupdriver
    become: yes
    file:
      path: /etc/docker/daemon.json
      state: touch
      mode: u+rw,g+r,o+r

  - name: Copiando arquivo e ajustando permissões
    become: yes
    ansible.builtin.copy:
      src: /home/rogerio/repos/meus-repos/ansible/ansible-k8s/k8s-ansible-project/tasks/daemon.json
      dest: /etc/docker/daemon.json
      owner: root
      group: root
      mode: '0644'

  - name: Restart service daemon-reload
    become: yes
    ansible.builtin.systemd:
      daemon_reload: yes
    
  - name: Restart service Docker
    become: yes
    ansible.builtin.systemd:
      name: docker
      state: restarted

  - name: Create a directory docker.service.d
    become: yes    
    file:
      path: /etc/systemdsystem/docker.service.d
      state: directory
      mode: '0755'

  - name: Restart service daemon-reload
    become: yes
    ansible.builtin.systemd:
      daemon_reload: yes
    
  - name: Restart service Docker
    become: yes
    ansible.builtin.systemd:
      name: docker
      state: restarted